# Generated by Django 4.0.1 on 2022-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('LoaiHinh', models.CharField(max_length=100)),
                ('TacGia', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=20)),
                ('Gia', models.CharField(max_length=100)),
                ('DienTich', models.CharField(blank=True, max_length=100)),
                ('DiaChi', models.CharField(max_length=100)),
                ('ChungNhanSoHuu', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
