# Generated by Django 4.0.1 on 2022-08-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
    ]
